resolver: lts-22.27

packages:
- .


extra-deps:
- stm-containers-1.2.1
- stm-hamt-1.2.1
- primitive-extras-0.10.2
- req-3.13.1
- crypton-1.0.0


allow-newer: true

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []